spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

server:
  port: 8080
